config:
    oauth2:
        accessTokenUri: http://localhost:9091/oauth/token
        userAuthorizationUri: http://localhost:9091/oauth/authorize
        leftMenu: http://localhost:9091/resources/user/leftmenu
        relatedUsers: http://localhost:9091/resources/user/relatedusers
        # 目前不考虑单点登录，如果考虑单点登录，则不合适使用login这套流程
        domainName: localhost #用于保证单点登录的实现，在不同的子系统之间，但是为了保证唯一性，以cookie为首要准则
        path: / #用于保证单点登录的实现，在不同的子系统之间，但是为了保证唯一性，以cookie为首要准则
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

security:
    basic:
        enabled: false
    oauth2:
           resource:
               jwt:
                   # Tells the JWT framework to fetch the public key from the authorization server during startup
                   # Note: The authorization server needs to be running...
                   #key-uri: "http://localhost:9091/oauth/token_key"\
                    key-value: |
                        -----BEGIN PUBLIC KEY-----
                        MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQDNQZKqTlO/+2b4ZdhqGJzGBDlt
                        b5PZmBz1ALN2YLvt341pH6i5mO1V9cX5Ty1LM70fKfnIoYUP4KCE33dPnC7LkUwE
                        /myh1zM6m8cbL5cYFPyP099thbVxzJkjHWqywvQih/qOOjliomKbM9pxG8Z1dB26
                        hL9dSAZuA8xExjlPmQIDAQAB
                        -----END PUBLIC KEY-----
