server:
    port: 9090
    contextPath: /oauth2client
config:
    oauth2:
        # as a sample to test
        clientID: test_client
        clientSecret: secret
        clientScopes:
               - internal_client
        clientUseCurrentUri: true
