server:
    port: 9090
    contextPath: /
config:
    oauth2:
        # as a sample to test
        clientID: cms_admin_client
        clientSecret: secret
        clientScopes:
                  - cms_admin_client
                  - internal_client