spring:
  redis:
    host: 115.28.238.211
    password: redis
    port: 6379
    pool:
      max-active: 8
common:
        pageSize: 10
        relatedusers: http://localhost:9091/user/user/list/relatedusers/options
        imageUpload: http://utils.hopever.cn/upload/image
        fileUpload: http://utils.hopever.cn/upload/file
        docUpload: http://utils.hopever.cn/upload/doc
        imageDel: http://utils.hopever.cn/delete/image
        fileDel: http://utils.hopever.cn/delete/file
        docDel: http://utils.hopever.cn/delete/doc
        imagePathPrev: http://www.hopever.cn/mogilefs/images/
        filePathPrev:  http://www.hopever.cn/mogilefs/files/
        docPathPrev:  http://www.hopever.cn/mogilefs/docs/
        defaultUserPhoto: http://localhost/utils/images/user/defaultphoto.png
