server:
    port: 9092
    contextPath: /
config:
    oauth2:
        # as a sample to test
        clientID: cms_client
        clientSecret: cms_client
        clientScopes:
                  - internal_client
        clientUseCurrentUri: true
    cms:
        staticResourcePath: C:\\xampp\\htdocs\\cms_basic\\
        #staticResourcePath: /usr/local/nginx/html/cms_basic/
        staticResourceRelativePath: http://localhost/cms_basic/
        #staticResourcePath: http://localhost/cms_basic/
